import PDFDocument from "pdfkit";
import fs from "fs";
import { CvAnalysis, MockInterview, UserProgress } from "@shared/schema";

export interface FeedbackReportData {
  user: {
    fullName: string;
    email: string;
  };
  progress: UserProgress;
  cvAnalyses: CvAnalysis[];
  mockInterviews: MockInterview[];
}

export async function generateFeedbackReport(data: FeedbackReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument();
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));

      // Header
      doc.fontSize(24).text("InterviewIQ Feedback Report", { align: "center" });
      doc.moveDown();

      // User Information
      doc.fontSize(16).text(`User: ${data.user.fullName}`, { align: "left" });
      doc.fontSize(12).text(`Email: ${data.user.email}`);
      doc.text(`Generated: ${new Date().toLocaleDateString()}`);
      doc.moveDown();

      // Progress Overview
      doc.fontSize(18).text("Progress Overview");
      doc.fontSize(12);
      doc.text(`CV Score: ${data.progress.cvScore}/100`);
      doc.text(`Total Mock Interviews: ${data.progress.interviewCount}`);
      doc.text(`Average Interview Score: ${data.progress.averageScore}/10`);
      doc.text(`Current Streak: ${data.progress.dayStreak} days`);
      doc.moveDown();

      // CV Analyses
      if (data.cvAnalyses.length > 0) {
        doc.fontSize(18).text("CV Analysis Results");
        doc.moveDown();

        data.cvAnalyses.forEach((analysis, index) => {
          doc.fontSize(14).text(`Analysis #${index + 1} - ${analysis.filename}`);
          doc.fontSize(12);
          doc.text(`Score: ${analysis.score}/100`);
          doc.text(`Date: ${analysis.createdAt?.toLocaleDateString()}`);
          
          if (Array.isArray(analysis.suggestions)) {
            doc.text("Suggestions:");
            (analysis.suggestions as string[]).forEach((suggestion, idx) => {
              doc.text(`${idx + 1}. ${suggestion}`, { indent: 20 });
            });
          }
          doc.moveDown();
        });
      }

      // Mock Interviews
      if (data.mockInterviews.length > 0) {
        doc.fontSize(18).text("Mock Interview Results");
        doc.moveDown();

        data.mockInterviews.forEach((interview, index) => {
          doc.fontSize(14).text(`Interview #${index + 1} - ${interview.jobRole}`);
          doc.fontSize(12);
          doc.text(`Question: ${interview.question}`);
          doc.text(`Score: ${interview.score}/10`);
          doc.text(`Date: ${interview.createdAt?.toLocaleDateString()}`);
          doc.text("Feedback:");
          doc.text(interview.feedback, { indent: 20 });
          
          if (interview.improvedAnswer) {
            doc.text("Improved Answer:");
            doc.text(interview.improvedAnswer, { indent: 20 });
          }
          doc.moveDown();
        });
      }

      // Footer
      doc.fontSize(10).text("Generated by InterviewIQ - AI-Powered Career Preparation Platform", {
        align: "center",
      });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
